### PR TITLE
add GeneratePDFButton2 and make borders

### PR DESCRIPTION
**Pull request by vadim9999**

### CODE REVIEW

**Comment by atherdon** [comment]
please rebase it

**Comment by vadim9999** [comment]
or we can use border like this 
image

**Comment by atherdon** [comment]
ok, looks i update it correctly. merging

**Comment by atherdon** [comment]
hold on, i'll review it on my side first. because i also coding at the same files - so i'm confusing both of us :)
let's continue tomorrow - it's late

**Pull request merged**
