### PR TITLE
add downloading pdf

### PR DESCRIPTION
**Pull request by vadim9999**
Downloading pdf that contains grocery with departments and their ingredients. Downloading button you will find when open a tile.

### CODE REVIEW

**Comment by vadim9999** [comment]
When I tried to install repo it was crushed in windows, I added a package "yoga-layout". Now it's works fine. Also I tried install with yarn it's also crushed. I think it's from "yoga-layout"

**Comment by atherdon** [comment]
I catch a similar issue few times with our projects. I think this is some sort of issue, that will be fixed by package maintainers. I think it's an issue with yarn or other big projects. Not sure if it was solved, because if you check travis ci build(that used yarn https://travis-ci.org/GroceriStar/showcase/builds/435321046?utm_source=github_status&utm_medium=notification) crashed, so it's not work

**Comment by atherdon** [comment]
Btw, second time i find out that you're not fetching a last changes from master branch. you can check it here: https://github.com/GroceriStar/showcase/pull/42/commits/59444a7698f6fcbe8e0aaf8d8185973d9d7ac05b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R32

please rebase your branch and also fetch changes more frequently.
then i'll merge your changes

**Comment by atherdon** [comment]
can you also install yoga for windows module? maybe it'll solve our build problems

**Pull request merged**
